package entities;
// Generated 21 ene. 2019 19:42:04 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Reservation generated by hbm2java
 */
public class Reservation implements java.io.Serializable {

	private Integer idReservation;
	private Client client;
	private String startDate;
	private String endDate;
	private Set cars = new HashSet(0);

	public Reservation() {
	}

	public Reservation(Client client, String startDate, String endDate, Set cars) {
		this.client = client;
		this.startDate = startDate;
		this.endDate = endDate;
		this.cars = cars;
	}

	public Integer getIdReservation() {
		return this.idReservation;
	}

	public void setIdReservation(Integer idReservation) {
		this.idReservation = idReservation;
	}

	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	public String getStartDate() {
		return this.startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	public String getEndDate() {
		return this.endDate;
	}

	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}

	public Set getCars() {
		return this.cars;
	}

	public void setCars(Set cars) {
		this.cars = cars;
	}

}
