package entities;
// Generated 21 ene. 2019 19:42:04 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
@SuppressWarnings({ "serial", "rawtypes" })
public class Client implements java.io.Serializable {

	private String dni;
	private String name;
	private String address;
	private String phone;
	private Set reservations = new HashSet(0);

	public Client() {
	}

	public Client(String dni) {
		this.dni = dni;
	}

	public Client(String dni, String name, String address, String phone, Set reservations) {
		this.dni = dni;
		this.name = name;
		this.address = address;
		this.phone = phone;
		this.reservations = reservations;
	}

	public String getDni() {
		return this.dni;
	}

	public void setDni(String dni) {
		this.dni = dni;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public Set getReservations() {
		return this.reservations;
	}

	public void setReservations(Set reservations) {
		this.reservations = reservations;
	}

}
